[package]
name = "spongefish-pow"
version = "0.1.0-alpha"
edition = "2021"
authors = [
    "Giacomo Fenzi <giacomofenzi@outlook.com>",
    "Remco Bloemen <remco@wicked.ventures>",
]
license = "BSD-3-Clause"

[lints]
workspace = true

[dependencies]
spongefish = { path = "../spongefish" }
blake3 = { workspace = true, optional = true }
keccak = { workspace = true, optional = true }
bytemuck = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }
rand = { workspace = true }

[features]
default = ["parallel", "blake3", "keccak"]
parallel = ["dep:rayon"]
blake3 = ["dep:blake3", "spongefish/blake3"]
keccak = ["dep:keccak", "dep:bytemuck", "spongefish/keccak"]
